# coding: utf-8

"""
    Aeternity Testnet

    This is the [Aeternity](https://www.aeternity.com/) Testnet API.

    OpenAPI spec version: 1.0.0
    Contact: apiteam@aeternity.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Account(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pubkey': 'str',
        'balance': 'int',
        'nonce': 'int',
        'height': 'int',
        'bets': 'int',
        'shares': 'int'
    }

    attribute_map = {
        'pubkey': 'pubkey',
        'balance': 'balance',
        'nonce': 'nonce',
        'height': 'height',
        'bets': 'bets',
        'shares': 'shares'
    }

    def __init__(self, pubkey=None, balance=None, nonce=None, height=None, bets=None, shares=None):
        """
        Account - a model defined in Swagger
        """

        self._pubkey = None
        self._balance = None
        self._nonce = None
        self._height = None
        self._bets = None
        self._shares = None

        if pubkey is not None:
          self.pubkey = pubkey
        if balance is not None:
          self.balance = balance
        if nonce is not None:
          self.nonce = nonce
        if height is not None:
          self.height = height
        if bets is not None:
          self.bets = bets
        if shares is not None:
          self.shares = shares

    @property
    def pubkey(self):
        """
        Gets the pubkey of this Account.

        :return: The pubkey of this Account.
        :rtype: str
        """
        return self._pubkey

    @pubkey.setter
    def pubkey(self, pubkey):
        """
        Sets the pubkey of this Account.

        :param pubkey: The pubkey of this Account.
        :type: str
        """

        self._pubkey = pubkey

    @property
    def balance(self):
        """
        Gets the balance of this Account.

        :return: The balance of this Account.
        :rtype: int
        """
        return self._balance

    @balance.setter
    def balance(self, balance):
        """
        Sets the balance of this Account.

        :param balance: The balance of this Account.
        :type: int
        """

        self._balance = balance

    @property
    def nonce(self):
        """
        Gets the nonce of this Account.

        :return: The nonce of this Account.
        :rtype: int
        """
        return self._nonce

    @nonce.setter
    def nonce(self, nonce):
        """
        Sets the nonce of this Account.

        :param nonce: The nonce of this Account.
        :type: int
        """

        self._nonce = nonce

    @property
    def height(self):
        """
        Gets the height of this Account.

        :return: The height of this Account.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """
        Sets the height of this Account.

        :param height: The height of this Account.
        :type: int
        """

        self._height = height

    @property
    def bets(self):
        """
        Gets the bets of this Account.

        :return: The bets of this Account.
        :rtype: int
        """
        return self._bets

    @bets.setter
    def bets(self, bets):
        """
        Sets the bets of this Account.

        :param bets: The bets of this Account.
        :type: int
        """

        self._bets = bets

    @property
    def shares(self):
        """
        Gets the shares of this Account.

        :return: The shares of this Account.
        :rtype: int
        """
        return self._shares

    @shares.setter
    def shares(self, shares):
        """
        Sets the shares of this Account.

        :param shares: The shares of this Account.
        :type: int
        """

        self._shares = shares

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Account):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
