# coding: utf-8

"""
    Aeternity Testnet

    This is the [Aeternity](https://www.aeternity.com/) Testnet API.

    OpenAPI spec version: 1.0.0
    Contact: apiteam@aeternity.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ChannelSync(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pubkey': 'str',
        'sig': 'str'
    }

    attribute_map = {
        'pubkey': 'pubkey',
        'sig': 'sig'
    }

    def __init__(self, pubkey=None, sig=None):
        """
        ChannelSync - a model defined in Swagger
        """

        self._pubkey = None
        self._sig = None

        if pubkey is not None:
          self.pubkey = pubkey
        if sig is not None:
          self.sig = sig

    @property
    def pubkey(self):
        """
        Gets the pubkey of this ChannelSync.

        :return: The pubkey of this ChannelSync.
        :rtype: str
        """
        return self._pubkey

    @pubkey.setter
    def pubkey(self, pubkey):
        """
        Sets the pubkey of this ChannelSync.

        :param pubkey: The pubkey of this ChannelSync.
        :type: str
        """

        self._pubkey = pubkey

    @property
    def sig(self):
        """
        Gets the sig of this ChannelSync.

        :return: The sig of this ChannelSync.
        :rtype: str
        """
        return self._sig

    @sig.setter
    def sig(self, sig):
        """
        Sets the sig of this ChannelSync.

        :param sig: The sig of this ChannelSync.
        :type: str
        """

        self._sig = sig

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ChannelSync):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
