# coding: utf-8

"""
    Aeternity Testnet

    This is the [Aeternity](https://www.aeternity.com/) Testnet API.

    OpenAPI spec version: 1.0.0
    Contact: apiteam@aeternity.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NewChannelWithServer(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ip': 'str',
        'port': 'int',
        'channel_id': 'int',
        'balance': 'int',
        'receive_limit': 'int',
        'fee': 'int',
        'delay': 'int'
    }

    attribute_map = {
        'ip': 'ip',
        'port': 'port',
        'channel_id': 'channel-id',
        'balance': 'balance',
        'receive_limit': 'receive-limit',
        'fee': 'fee',
        'delay': 'delay'
    }

    def __init__(self, ip=None, port=None, channel_id=None, balance=None, receive_limit=None, fee=None, delay=None):
        """
        NewChannelWithServer - a model defined in Swagger
        """

        self._ip = None
        self._port = None
        self._channel_id = None
        self._balance = None
        self._receive_limit = None
        self._fee = None
        self._delay = None

        if ip is not None:
          self.ip = ip
        if port is not None:
          self.port = port
        if channel_id is not None:
          self.channel_id = channel_id
        if balance is not None:
          self.balance = balance
        if receive_limit is not None:
          self.receive_limit = receive_limit
        if fee is not None:
          self.fee = fee
        if delay is not None:
          self.delay = delay

    @property
    def ip(self):
        """
        Gets the ip of this NewChannelWithServer.

        :return: The ip of this NewChannelWithServer.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """
        Sets the ip of this NewChannelWithServer.

        :param ip: The ip of this NewChannelWithServer.
        :type: str
        """

        self._ip = ip

    @property
    def port(self):
        """
        Gets the port of this NewChannelWithServer.

        :return: The port of this NewChannelWithServer.
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """
        Sets the port of this NewChannelWithServer.

        :param port: The port of this NewChannelWithServer.
        :type: int
        """

        self._port = port

    @property
    def channel_id(self):
        """
        Gets the channel_id of this NewChannelWithServer.

        :return: The channel_id of this NewChannelWithServer.
        :rtype: int
        """
        return self._channel_id

    @channel_id.setter
    def channel_id(self, channel_id):
        """
        Sets the channel_id of this NewChannelWithServer.

        :param channel_id: The channel_id of this NewChannelWithServer.
        :type: int
        """

        self._channel_id = channel_id

    @property
    def balance(self):
        """
        Gets the balance of this NewChannelWithServer.

        :return: The balance of this NewChannelWithServer.
        :rtype: int
        """
        return self._balance

    @balance.setter
    def balance(self, balance):
        """
        Sets the balance of this NewChannelWithServer.

        :param balance: The balance of this NewChannelWithServer.
        :type: int
        """

        self._balance = balance

    @property
    def receive_limit(self):
        """
        Gets the receive_limit of this NewChannelWithServer.

        :return: The receive_limit of this NewChannelWithServer.
        :rtype: int
        """
        return self._receive_limit

    @receive_limit.setter
    def receive_limit(self, receive_limit):
        """
        Sets the receive_limit of this NewChannelWithServer.

        :param receive_limit: The receive_limit of this NewChannelWithServer.
        :type: int
        """

        self._receive_limit = receive_limit

    @property
    def fee(self):
        """
        Gets the fee of this NewChannelWithServer.

        :return: The fee of this NewChannelWithServer.
        :rtype: int
        """
        return self._fee

    @fee.setter
    def fee(self, fee):
        """
        Sets the fee of this NewChannelWithServer.

        :param fee: The fee of this NewChannelWithServer.
        :type: int
        """

        self._fee = fee

    @property
    def delay(self):
        """
        Gets the delay of this NewChannelWithServer.

        :return: The delay of this NewChannelWithServer.
        :rtype: int
        """
        return self._delay

    @delay.setter
    def delay(self, delay):
        """
        Sets the delay of this NewChannelWithServer.

        :param delay: The delay of this NewChannelWithServer.
        :type: int
        """

        self._delay = delay

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NewChannelWithServer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
